-- Creación de la tabla provincia
CREATE TABLE IF NOT EXISTS provincia (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    poblacion INT NOT NULL
);

-- Inserción de las provincias
INSERT INTO provincia (nombre, descripcion, poblacion) VALUES
('Álava', 'Provincia en el norte de España, en la comunidad autónoma del País Vasco', 331000),
('Albacete', 'Provincia en el este de España, en la comunidad autónoma de Castilla-La Mancha', 174000),
('Alicante', 'Provincia en la comunidad Valenciana, en la costa este de España', 1860000),
('Almería', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 720000),
('Asturias', 'Provincia en el norte de España, en la comunidad autónoma del Principado de Asturias', 1020000),
('Ávila', 'Provincia en el centro de España, en la comunidad autónoma de Castilla y León', 160000),
('Badajoz', 'Provincia en el suroeste de España, en la comunidad autónoma de Extremadura', 693000),
('Barcelona', 'Provincia en la costa este de España, en la comunidad autónoma de Cataluña', 5530000),
('Burgos', 'Provincia en el norte de España, en la comunidad autónoma de Castilla y León', 356000),
('Cáceres', 'Provincia en el oeste de España, en la comunidad autónoma de Extremadura', 410000),
('Cádiz', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 1260000),
('Cantabria', 'Provincia en el norte de España, en la comunidad autónoma de Cantabria', 600000),
('Castellón', 'Provincia en la comunidad Valenciana, en la costa este de España', 600000),
('Ceuta', 'Ciudad autónoma de España, ubicada en la costa norte de África', 85000),
('Ciudad Real', 'Provincia en el centro de España, en la comunidad autónoma de Castilla-La Mancha', 500000),
('Córdoba', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 800000),
('Cuenca', 'Provincia en el centro de España, en la comunidad autónoma de Castilla-La Mancha', 200000),
('Gerona', 'Provincia en la comunidad autónoma de Cataluña, en el noreste de España', 760000),
('Granada', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 920000),
('Guadalajara', 'Provincia en el centro de España, en la comunidad autónoma de Castilla-La Mancha', 260000),
('Gipuzkoa', 'Provincia en el norte de España, en la comunidad autónoma del País Vasco', 720000),
('Huelva', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 500000),
('Huesca', 'Provincia en el norte de España, en la comunidad autónoma de Aragón', 220000),
('Islas Baleares', 'Provincia insular en el mar Mediterráneo, en las Islas Baleares', 1150000),
('Jaén', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 630000),
('La Rioja', 'Provincia en el norte de España, en la comunidad autónoma de La Rioja', 320000),
('Las Palmas', 'Provincia en las Islas Canarias, en el océano Atlántico', 1100000),
('León', 'Provincia en el noroeste de España, en la comunidad autónoma de Castilla y León', 470000),
('Lleida', 'Provincia en la comunidad autónoma de Cataluña, en el noreste de España', 430000),
('Madrid', 'Provincia central de España', 6642000),
('Málaga', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 1700000),
('Murcia', 'Provincia en el sureste de España, en la comunidad autónoma de Murcia', 1500000),
('Navarra', 'Provincia en el norte de España, en la comunidad autónoma de Navarra', 650000),
('Ourense', 'Provincia en el noroeste de España, en la comunidad autónoma de Galicia', 300000),
('Palencia', 'Provincia en el norte de España, en la comunidad autónoma de Castilla y León', 160000),
('Pontevedra', 'Provincia en el noroeste de España, en la comunidad autónoma de Galicia', 950000),
('Salamanca', 'Provincia en el oeste de España, en la comunidad autónoma de Castilla y León', 350000),
('Santa Cruz de Tenerife', 'Provincia en las Islas Canarias, en el océano Atlántico', 1000000),
('Segovia', 'Provincia en el centro de España, en la comunidad autónoma de Castilla y León', 160000),
('Sevilla', 'Provincia en el sur de España, en la comunidad autónoma de Andalucía', 1940000),
('Soria', 'Provincia en el norte de España, en la comunidad autónoma de Castilla y León', 88000),
('Tarragona', 'Provincia en la comunidad autónoma de Cataluña, en el noreste de España', 800000),
('Teruel', 'Provincia en el este de España, en la comunidad autónoma de Aragón', 140000),
('Toledo', 'Provincia en el centro de España, en la comunidad autónoma de Castilla-La Mancha', 700000),
('Valencia', 'Provincia en la costa este de España, en la comunidad autónoma de Valencia', 2580000),
('Valladolid', 'Provincia en el noroeste de España, en la comunidad autónoma de Castilla y León', 520000),
('Vizcaya', 'Provincia en el norte de España, en la comunidad autónoma del País Vasco', 1150000),
('Zamora', 'Provincia en el noroeste de España, en la comunidad autónoma de Castilla y León', 160000),
('Zaragoza', 'Provincia en el noreste de España, en la comunidad autónoma de Aragón', 976000);
